apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cron
        spec:              
          restartPolicy: OnFailure
          containers:
          - name: test
            image: alpine
            command: ["curl"]
            args: ["https://google.com"]
