apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-dp
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cache-dp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cache-dp
    spec:
      containers:
        - name: memcached
          image: memcached
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            requests:
              cpu: "1"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "128Mi"      
        - name: redis
          image: redis
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            requests:
              cpu: "1"
              memory: "4Gi"
            limits:
              cpu: "1"           
              memory: "4Gi"    
