apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-dp
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: httpd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: httpd
    spec:
      nodeSelector:
         dedicated: true
      tolerations:
        - key: "usercase"
          operator: "Equal"
          value: "workload"
          effect: "NoSchedule"      
      containers:
        - name: httpd
          image: httpd
