apiVersion: v1
kind: Pod
metadata:
  name: redis-kv
  label: redis
spec:
  containers:
  - image: redis
    name: redis
    volumeMounts:
      - name: nfs-pvc
        mountPath: "/data"
  - image: bitnami/redis-exporter:latest
    name: redis-exporter
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: nfs-data
  
